### ISSUE TITLE
No topbar rounded corners

### ISSUE THREAD

**Issue by nicknickeryt** [aunetx/panel-corners#3]
It seems like they're being drawn on top of the panel instead of being rendered below it. The corners could be seen in overview mode.
![image](https://user-images.githubusercontent.com/37023408/154232310-a7609a29-1136-441e-89f2-906213dbe94b.png)
![image](https://user-images.githubusercontent.com/37023408/154232373-a5b8c0d9-f32c-4ae9-aa3e-a65a11f139c7.png)
![Screenshot from 2022-02-16 10-11-41(1)](https://user-images.githubusercontent.com/37023408/154232845-a77ae8b4-be58-4f7c-bd95-67067bcacc00.png)

**Comment by aunetx** [comment]
Thanks for opening the issue, I don't fully understand it.

Do you mean that there is no panel corners (ie rounded corners between the panel and the rest of the desktop)? If this is the case then it is problematic, indeed :)

Do you use any other extension, and if yes, does the extension works when everything else is disabled?

What you see in overview is the screen corners, which are rendered even in overview -- so if I did not misunderstand, it looks like no panel corners exist at all.

**Comment by nicknickeryt** [comment]
> Do you mean that there is no panel corners (ie rounded corners between the panel and the rest of the desktop)? If this is the case then it is problematic, indeed :)

yep, that's the point

> Do you use any other extension, and if yes, does the extension works when everything else is disabled

I have Alphabethical App Grid and AppIndicator and KStatusNotifierItem support installed, but even if I disable them, the extension doesn't work and there are no rounded corners.

I use Arch (btw!) with gnome alpha/beta packages from [fcgu](https://gitlab.com/fabiscafe/gnome-unstable) repo if that helps.

**Comment by nicknickeryt** [comment]
And I mean I'm able to see rounded corners at the bottom but when I switch to overview I can also see them at the top. If you look closely you can see them being rendered correctly at the top here:
![image](https://user-images.githubusercontent.com/37023408/155210108-6c9104a2-4f92-4506-aba7-e9e1f6259962.png)
Leaving overview makes the corners at the top disappear.

**Comment by aunetx** [comment]
Thanks for the answer :)

Could you try with last commit? You can install with `make install`, I had a hard time debugging this but I finally changed the way the corners are placed so that it is compatible with gnome 42.

**Comment by aunetx** [comment]
And btw for the corners at the top, this is normal and these are the screen corners (independent of the panel), drawn on each monitor, even in overview :)

**Comment by aunetx** [comment]
This should be closed now :)

**Comment by nicknickeryt** [comment]
Yeah, I can confirm it's working now. Thanks!
