### ISSUE TITLE
version 10 doesn't work

### ISSUE THREAD

**Issue by v-tibi** [aunetx/panel-corners#33]
It just stopped working altogether after updating to version 10.

**Comment by aunetx** [comment]
Which version of gnome do you use? And do you see any logs related to panels-corner?

**Comment by v-tibi** [comment]
> Which version of gnome do you use? And do you see any logs related to panels-corner?

Sorry for the lack of information. I'm running Ubuntu 23.10 with GNOME Shell 45.2.
I didn't check any logs yet. As I see it on extensions.gnome.org I'm not the only one with this problem. What logs should I check?

**Comment by danielpabeda** [comment]
Same problem!

**Comment by aunetx** [comment]
Thanks, I though the version for GNOME 46 would be backward-compatible, apparently not! I will remove it right now

**Comment by aunetx** [comment]
I pushed the corrected version to extensions.gnome.org, please reopen this if the issue reappears after the update

**Comment by celsotavaresdev** [comment]
> Thanks, I though the version for GNOME 46 would be backward-compatible, apparently not! I will remove it right now



> I pushed the corrected version to extensions.gnome.org, please reopen this if the issue reappears after the update

Tested and Working perfectly, thank you!
