### ISSUE TITLE
TypeError: prefsModule.buildPrefsWidget is not a function

### ISSUE THREAD

**Issue by yochananmarqos** [aunetx/panel-corners#7]
The new preferences with v4 (d933ed0) is not opening:

Manjaro GNOME
GNOME Shell 41.4

The settings of extension panel-corners@aunetx had an error:
```
TypeError: prefsModule.buildPrefsWidget is not a function
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by aunetx** [comment]
Hello, how did you install this version? Version 4 is not available one gnome 40 and 41, it is only intended for gnome 42 -- as I built the preferences using libadwaita.

Future versions should normally be compatible with 40 and 41 again, but this particular one is not -- at least, preferences will not work; everything else will.

**Comment by yochananmarqos** [comment]
Ah, I see. I update from the latest commit. Which commit should I revert to until GNOME 42 is out?

**Comment by yochananmarqos** [comment]
I'm currently testing GNOME 42 and it's working well.
